apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.5.2
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
        - name: ingressShim.defaultIssuerName
          value: letsencrypt-prod
        - name: ingressShim.defaultIssuerKind
          value: ClusterIssuer
        - name: ingressShim.defaultIssuerGroup
          value: cert-manager.io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true