
{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "debian-cloud-image-finder.fullname" . }}
  labels:
    app: {{ template "debian-cloud-image-finder.name" . }}
    chart: {{ template "debian-cloud-image-finder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.app.secretKey }}
  secretKey: {{ .Values.app.secretKey | b64enc | quote }}
  {{- else }}
  secretKey: {{ randAlphaNum 30 | b64enc | quote }}
  {{- end }}
  gitlabClientId: {{ .Values.app.gitlabClientId | b64enc | quote }}
  gitlabClientSecret: {{ .Values.app.gitlabClientSecret | b64enc | quote }}
{{- end }}